version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
<<<<<<< HEAD
<<<<<<< HEAD
    build-and-test:
      jobs:
        - build-and-test
=======
  build-and-test:
    jobs:
      - build-and-test
>>>>>>> b498297... fix: revert ci
=======
  build-and-test:
    jobs:
      - build-and-test
>>>>>>> 3e8b9fe... fix: ci pipeline
